language: python

env:
  - COMPOSE_FILE=docker-compose.test.yml
  - PATH="~/.local/bin:$PATH"

services:
  - docker

before_install:
  - pip install --user --upgrade docker-compose
  - docker-compose version

script:
  - docker-compose run --rm sut
